# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [2]:
import numpy as np
np.__version__

'1.21.6'



---



## 배열 생성

### 리스트로 배열 만들기


In [ ]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [ ]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a2)
print(a2.shape)
print(a2[0], a2[1], a2[2])
print(a2[0, 0], a2[1, 1], a2[2, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[1 2 3] [4 5 6] [7 8 9]
1 5 8


In [ ]:
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]],
               [[1,2,3], [4,5,6], [7,8,9]],
               [[1,2,3], [4,5,6], [7,8,9]]])
print(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [ ]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [ ]:
np.full((3, 3),1.45)

array([[1.45, 1.45, 1.45],
       [1.45, 1.45, 1.45],
       [1.45, 1.45, 1.45]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [ ]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [ ]:
np.empty(10)

array([2.00724327e-316, 1.77863633e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.38028790e-071, 1.38058779e-047, 7.78718396e-091,
       2.09197954e-076, 4.50788113e-315])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [ ]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [ ]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
print(a3)
np.full_like(a3,10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [ ]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [ ]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [ ]:
np.random.random((3,3))

array([[0.38345466, 0.51780534, 0.37370562],
       [0.56066392, 0.15250635, 0.61835671],
       [0.53681452, 0.31913064, 0.19897505]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [ ]:
np.random.randint(0, 10, (3, 3))

array([[3, 3, 2],
       [1, 6, 5],
       [0, 8, 9]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [ ]:
np.random.normal(0, 1, (3,3))

array([[-0.51938385, -1.09676539,  2.30710025],
       [-0.43807875, -0.60500523, -0.38635046],
       [ 0.92829854,  0.42075081, -1.02529978]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.rand(3,3)

array([[0.54118883, 0.38302583, 0.32292306],
       [0.38719985, 0.78306052, 0.58866307],
       [0.74085921, 0.14697679, 0.32240913]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.randn(3,3)

array([[ 0.3227986 ,  0.03822479,  1.60302891],
       [-0.3576308 , -2.33261111,  0.92092329],
       [ 0.84923828, -0.89197798, -1.84432451]])

### 표준 데이터 타입

In [ ]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.full((3,3), 1.0, dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [ ]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [ ]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [ ]:
datetime = np.datetime64('2020-06-20 12:00')
datetime

numpy.datetime64('2020-06-20T12:00')

In [ ]:
datetime = np.datetime64('2022-09-22 11:00:13.44', 'ns')
datetime

numpy.datetime64('2022-09-22T11:00:13.440000000')



---



## 배열 조회

### 배열 속성 정보

In [ ]:
def array_info(array):
  print(array)
  print('ndim:', array.ndim)
  print('shape:', array.shape)
  print('dtye:', array.dtype)
  print('size:', array.size)
  print('itemsize:', array.itemsize) #item bites
  print('nbytes:', array.nbytes) #전체 배열의 bites
  print('strides:', array.strides) #다음 차원으로 넘어가기 위해 필요한 byte

In [ ]:
array_info(a1)

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtye: int64
size: 5
itemsize: 8
nbytes: 40
strides: (8,)


In [ ]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtye: int64
size: 9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [ ]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtye: int64
size: 27
itemsize: 8
nbytes: 216
strides: (72, 24, 8)


### 인덱싱(Indexing)

In [ ]:
print(a1)
print(a1[2])
print(a1[-1])

[4 5 6 4 5]
6
5


In [ ]:
print(a2)
print(a2[0, 2])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
9


In [ ]:
print(a3)
print(a3[0,0,0])
print(a3[2,1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
6


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [ ]:
print(a1)
print(a1[0:2])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4]
[5 4 6 5 4]
[4 6 5]


In [ ]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [ ]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [ ]:
print(a3)
bi = np.random.randint(0, 2, (3,3), dtype = bool)
print(bi)
print(a2[bi])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[False False False]
 [ True False  True]
 [False  True  True]]
[4 6 8 9]


### 팬시 인덱싱(Fancy Indedxing)

In [ ]:
print(a1)
print(a1[0], a1[2])
ind = [0,2]
print(a1[ind])
ind = np.array([[0,1], [2, 0]])
print(a1[ind])

[4 5 6 4 5]
4 6
[4 6]
[[4 5]
 [6 4]]


In [ ]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [ ]:
print(a1)
b1 = np.insert(a1, 0, 10) #원본, 위치값, 값, 축
print(b1)
print(a1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[4 5 6 4 5]
[ 4  5 10  6  4  5]


In [ ]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis = 1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [ ]:
a1 = np.array([4,5,6,4,5])
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)

[1 2 3 4 5]
[9 2 3 4 5]


In [ ]:
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[9 0 3 0 0]
[9 4 3 4 4]


In [ ]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
a2[0] = 1
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]


In [ ]:
a2[1:, 2] = 9
print(a2)
row = np.array([0,1])
col = np.array([1,2])
a2[row, col] = 0
print(a2)

[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [ ]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [ ]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=0)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [ ]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:,1]=2
print(a2_sub)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 2]
 [4 2]]
[[1 2 1]
 [4 2 0]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [ ]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[1 2 1]
 [4 2 0]
 [7 8 9]]
[[1 2]
 [4 2]]
[[1 1]
 [4 1]]
[[1 2 1]
 [4 2 0]
 [7 8 9]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [ ]:
print(a2)
print(a2.T)

[[1 2 1]
 [4 2 0]
 [7 8 9]]
[[1 4 7]
 [2 2 8]
 [1 0 9]]


In [ ]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [ ]:
print(a2)
print(a2.swapaxes(1,0))

[[1 2 1]
 [4 2 0]
 [7 8 9]]
[[1 4 7]
 [2 2 8]
 [1 0 9]]


In [ ]:
from numpy.linalg.linalg import swapaxes
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [ ]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [ ]:
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


* `flatten()`: 데이터 그대로 1차원으로 변경

In [ ]:
x = np.array(range(8)).reshape(2, 2, 2)
print(x)
print(x.flatten())

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[0 1 2 3 4 5 6 7]


### 배열 크기 변경

* 배열 모양만 변경

In [ ]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize((5,2))
print(n2)

[[9 3 9 3 2]
 [5 6 8 0 4]]
[[9 3]
 [9 3]
 [2 5]
 [6 8]
 [0 4]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [ ]:
n2.resize((5,5), refcheck=False)
print(n2)

[[9 3 9 3 2]
 [5 6 8 0 4]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [ ]:
n2.resize((3,3), refcheck=False)
print(n2)

[[9 3 9]
 [3 2 5]
 [6 8 0]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [ ]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
b2 = np.arange(10, 19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [ ]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [ ]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [ ]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [ ]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [ ]:
c1 = np.array([7,8,9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [ ]:
a2 = np.array([[1,2,3], [4,5,6]])
np.concatenate([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2 = np.array([[1,2,3], [4,5,6]])
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [ ]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [ ]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [ ]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [ ]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [ ]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2,4,6,8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2, c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]] [[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [ ]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2, c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]] [[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [ ]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3, c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]] [[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [ ]:
a1 = np.array([1,2,3])
print(a1)
print(a1+5)

[1 2 3]
[6 7 8]


In [ ]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print(a1 + a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [ ]:
b2 = np.array([1,2,3]).reshape(3, 1)
print(b2)
print(a1+b2)

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [3]:
a1 = np.arange(1, 10)
print(a1)

[1 2 3 4 5 6 7 8 9]


In [5]:
print(a1+1)
print(np.add(a1, 10))
print(a1-2)
print(np.subtract(a1, 10))
print(-a1) #단항 음수
print(np.negative(a1)) #단항 음수
print(a1*2)
print(np.multiply(a1, 2))
print(a1/2)
print(np.divide(a1, 2))
print(a1//2) #나눗셈 내림
print(np.floor_divide(a1, 2)) #나눗셈 내림
print(a1**2) #지수연산
print(np.power(a1, 2)) #지수연산
print(a1 % 2) #나머지 연산
print(np.mod(a1, 2)) #나머지 연산

[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [ ]:
a1 = np.arange(1, 10)
print(a1)
b1 = np.random.randint(1, 10, size=9)
print(b1)
print(a1 + b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[2 5 4 8 1 3 9 8 9]
[ 3  7  7 12  6  9 16 16 18]
[ 2 10 12 32  5 18 63 64 81]
[0.5        0.4        0.75       0.5        5.         2.
 0.77777778 1.         1.        ]
[0 0 0 0 5 2 0 1 1]
[1 2 3 4 0 0 7 0 0]


In [ ]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
b2 = np.random.randint(1, 10, (3,3))
print(b2)
print(a2+b2) #2차원에서도 동일하게 산술연산 가능

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 1 2]
 [4 5 7]
 [2 7 2]]
[[ 3  3  5]
 [ 8 10 13]
 [ 9 15 11]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [ ]:
a1 = np.random.randint(-10, 10, 5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[ 1 -6 -9  5  0]
[1 6 9 5 0]
[1 6 9 5 0]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [ ]:
a1 = np.array([1,2,3,4,5])
print(np.square(a1))
print(np.sqrt(a1))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]


#### 지수와 로그 함수 (Exponential and Log Function)

In [ ]:
a1 = np.random.randint(1, 10, 5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1)) 
print(np.power(a1,2)) #지수 

[8 9 2 1 5]
[2.98095799e+03 8.10308393e+03 7.38905610e+00 2.71828183e+00
 1.48413159e+02]
[256. 512.   4.   2.  32.]
[64 81  4  1 25]


In [ ]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[8 9 2 1 5]
[2.07944154 2.19722458 0.69314718 0.         1.60943791]
[3.         3.169925   1.         0.         2.32192809]
[0.90308999 0.95424251 0.30103    0.         0.69897   ]


#### 삼각 함수(Trigonometrical Function)


In [ ]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [ ]:
a2 = np.random.randint(1, 10, size=(3,3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
35 35
[13 14  8] [ 7 13 15]


#### cumsum(): 누적합 계산

In [ ]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
[ 2  5  7 11 16 20 27 33 35]
[[ 2  3  2]
 [ 6  8  6]
 [13 14  8]]
[[ 2  5  7]
 [ 4  9 13]
 [ 7 13 15]]


#### diff(): 차분 계산

In [ ]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
[[ 1 -1]
 [ 1 -1]
 [-1 -4]]
[[ 2  2  2]
 [ 3  1 -2]]
[[ 1 -1]
 [ 1 -1]
 [-1 -4]]


#### prod(): 곱 계산

In [ ]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
80640
[56 90 16]
[12 80 84]


#### cumprod(): 누적곱 계산

In [ ]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
[    2     6    12    48   240   960  6720 40320 80640]
[[ 2  3  2]
 [ 8 15  8]
 [56 90 16]]
[[ 2  6 12]
 [ 4 20 80]
 [ 7 42 84]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [ ]:
print(a2)
b2= np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 7  7  7]
 [13 13 13]
 [15 15 15]]
[[ 7  7  7]
 [13 13 13]
 [15 15 15]]


In [ ]:
x_1 = np.arange(1, 7).reshape(2,3)
x_2 = np.arange(1, 7).reshape(3,2)
print(x_1)
print(x_2)
print(x_1.dot(x_2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]


#### tensordot(): 텐서곱 계산

In [ ]:
print(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes=0))
print(np.tensordot(a2, b2, axes=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
35
[[[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]


 [[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]]
[[ 7  7  7]
 [13 13 13]
 [15 15 15]]


#### cross(): 벡터곱

In [ ]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x,y))

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [ ]:
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 7  7  7]
 [13 13 13]
 [15 15 15]]
[[2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3]
 [2 2 2 2 2 2 2 2 2]
 [4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5]
 [4 4 4 4 4 4 4 4 4]
 [7 7 7 7 7 7 7 7 7]
 [6 6 6 6 6 6 6 6 6]
 [2 2 2 2 2 2 2 2 2]]


#### mean(): 평균 계산

In [ ]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
3.888888888888889
[4.33333333 4.66666667 2.66666667]
[2.33333333 4.33333333 5.        ]


#### std(): 표준 편차 계산

In [ ]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
1.7284832429004495
[2.05480467 1.24721913 0.94280904]
[0.47140452 0.47140452 2.1602469 ]


#### var(): 분산 계산

In [ ]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
2.9876543209876547
[4.22222222 1.55555556 0.88888889]
[0.22222222 0.22222222 4.66666667]


#### min(): 최소값

In [ ]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
2
[2 3 2]
[2 4 2]


#### max(): 최대값

In [ ]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
7
[7 6 4]
[3 5 7]


#### argmin(): 최소값 인덱스

In [ ]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
0
[0 0 0]
[0 0 2]


#### argmax(): 최대값 인덱스

In [ ]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
6
[2 2 1]
[1 1 0]


#### median(): 중앙값

In [ ]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[2 3 2]
 [4 5 4]
 [7 6 2]]
4.0
[4. 5. 2.]
[2. 4. 6.]


#### percentile(): 백분위 수



In [ ]:
a1 = np.array([1,2,3,4])
print(a1)
print(np.percentile(a1, [1, 20, 40, 60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [1, 20, 40, 60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [1, 20, 40, 60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [1, 20, 40, 60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [1, 20, 40, 60, 80, 100], interpolation='midpoint'))

[1 2 3 4]
[1.03 1.6  2.2  2.8  3.4  4.  ]
[2 2 3 3 4 4]
[1 1 2 2 3 4]
[1 2 2 3 3 4]
[1.5 1.5 2.5 2.5 3.5 4. ]


#### any()

In [ ]:
a2 = np.array([[False, False, False],
               [False, True, True],
               [False, True, True]])
print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [ ]:
a2 = np.array([[False, False,True],
               [True, True, True],
               [False, True, True]])
print(a2)
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산(Comparison Operators)


In [ ]:
a1 = np.arange(1,10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[False False False False  True  True  True  True  True]


In [ ]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a1 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))
print(np.any(a2 > 5, axis=0))
print(np.any(a2 > 5, axis=1))
print(np.all(a2 > 5, axis=0))
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
[ True  True  True]
[False  True  True]
[False False False]
[False False  True]


### 비교범용함수
* np.isclose : 배열 두개가 (z*1e+02)% 내외로 가까우면 True, 아니면 False
* np.isinf : 배열이 inf이면 True, 아니면 False
* np.isfinite : 배열이 inf,nan이면 False, 아니면 True
* np.isnan : 배열이 nan이면 True, 아니면 False







In [ ]:
a1 = np.array([1,2,3,4,5])
print(a1)
b1 = np.array([1,2,3,3,4])
print(b1)
print(np.isclose(a1, b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [ ]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


     연산자        비교 범용함수
      &             np.bitwise_and
      |             np.bitwise_or
      ^             np.bitwise_xor
      ~             np.bitwise_not
                   

In [ ]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print((a2 > 5) & (a2 < 8)) #and
print(a2[(a2 > 5) & (a2 < 8)]) #True인 값만 출력

print((a2 > 5) | (a2 < 8)) #or
print(a2[(a2 > 5) | (a2 < 8)])

print((a2 > 5) ^ (a2 < 8)) #xor
print(a2[(a2 > 5) ^ (a2 < 8)])

print(~(a2 > 5)) #not
print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [ ]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1)) #정렬 index값
print(a1)
print(a1.sort())
print(a1)

[5 6 7 8 4 8 1 7 3 5]
[1 3 4 5 5 6 7 7 8 8]
[5 6 7 8 4 8 1 7 3 5]
[6 8 4 0 9 1 2 7 3 5]
[5 6 7 8 4 8 1 7 3 5]
None
[1 3 4 5 5 6 7 7 8 8]


In [ ]:
a2 = np.random.randint(1, 10, (3,3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[6 7 6]
 [2 6 1]
 [7 3 4]]
[[2 3 1]
 [6 6 4]
 [7 7 6]]
[[6 6 7]
 [1 2 6]
 [3 4 7]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [ ]:
a1 = np.random.randint(1, 10, 10)
print(a1)
print(np.partition(a1, 3))

[4 3 9 3 7 4 4 8 4 3]
[3 3 3 4 4 4 4 8 9 7]


In [ ]:
a2 = np.random.randint(1, 10, (5,5))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))

[[3 7 8 6 4]
 [5 5 3 1 8]
 [8 9 8 9 3]
 [5 9 2 1 2]
 [5 6 9 4 4]]
[[3 4 6 7 8]
 [1 3 5 5 8]
 [3 8 8 9 9]
 [1 2 2 5 9]
 [4 4 5 6 9]]
[[5 5 2 1 2]
 [3 6 8 4 3]
 [5 7 3 1 4]
 [5 9 8 6 4]
 [8 9 9 9 8]]
[[3 4 6 7 8]
 [1 3 5 5 8]
 [3 8 8 9 9]
 [1 2 2 5 9]
 [4 4 5 6 9]]


## 배열 입출력


|  함수   |  설명     |   파일종류   |  
|:---:   |:---:      |:---:|    
|np.save() | Numpy배열 객체 1개를 파일에 저장 |바이너리|
| np.savez() | Numpy배열 객체 여러개를 파일에 저장 | 바이너리|
| np.load() |Numpy 배열 저장 파일로부터 객체 로딩 | 바이너리|
| np.loadtxt() |텍스트 파일로부터 배열 로딩 | 텍스트|
| np.svaetxt()| 텍스프 파일에 Numpy 배열 객체 저정| 텍스트|

In [ ]:
a2 = np.random.randint(1, 10, size=(5,5))
print(a2)
np.save('a', a2)

[[9 2 5 8 4]
 [9 1 5 4 9]
 [5 9 2 2 3]
 [1 7 8 4 6]
 [3 3 7 8 8]]


In [ ]:
!ls

a.npy  sample_data


In [ ]:
b2 = np.random.randint(1, 10, (5,5))
print(b2)
np.savez("ab", a2, b2)

[[4 5 5 2 9]
 [4 4 5 6 2]
 [1 3 5 5 5]
 [1 1 1 6 1]
 [2 8 9 5 2]]


In [ ]:
!ls

ab.npz	a.npy  sample_data


In [ ]:
npy = np.load("a.npy")
print(npy)

[[9 2 5 8 4]
 [9 1 5 4 9]
 [5 9 2 2 3]
 [1 7 8 4 6]
 [3 3 7 8 8]]


In [ ]:
npz = np.load('ab.npz')
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[9 2 5 8 4]
 [9 1 5 4 9]
 [5 9 2 2 3]
 [1 7 8 4 6]
 [3 3 7 8 8]]
[[4 5 5 2 9]
 [4 4 5 6 2]
 [1 3 5 5 5]
 [1 1 1 6 1]
 [2 8 9 5 2]]


In [ ]:
print(a2)
np.savetxt('a.csv', a2, delimiter=',')

[[9 2 5 8 4]
 [9 1 5 4 9]
 [5 9 2 2 3]
 [1 7 8 4 6]
 [3 3 7 8 8]]


In [ ]:
!ls

ab.npz	a.csv  a.npy  sample_data


In [ ]:
!cat a.csv

9.000000000000000000e+00,2.000000000000000000e+00,5.000000000000000000e+00,8.000000000000000000e+00,4.000000000000000000e+00
9.000000000000000000e+00,1.000000000000000000e+00,5.000000000000000000e+00,4.000000000000000000e+00,9.000000000000000000e+00
5.000000000000000000e+00,9.000000000000000000e+00,2.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
1.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00,4.000000000000000000e+00,6.000000000000000000e+00
3.000000000000000000e+00,3.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00


In [ ]:
csv = np.loadtxt('a.csv', delimiter=',')
print(csv)

[[9. 2. 5. 8. 4.]
 [9. 1. 5. 4. 9.]
 [5. 9. 2. 2. 3.]
 [1. 7. 8. 4. 6.]
 [3. 3. 7. 8. 8.]]


In [ ]:
print(b2)
np.savetxt('b.csv', b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4, c5')

[[4 5 5 2 9]
 [4 4 5 6 2]
 [1 3 5 5 5]
 [1 1 1 6 1]
 [2 8 9 5 2]]


In [ ]:
!cat b.csv

# c1, c2, c3, c4, c5
4.00e+00,5.00e+00,5.00e+00,2.00e+00,9.00e+00
4.00e+00,4.00e+00,5.00e+00,6.00e+00,2.00e+00
1.00e+00,3.00e+00,5.00e+00,5.00e+00,5.00e+00
1.00e+00,1.00e+00,1.00e+00,6.00e+00,1.00e+00
2.00e+00,8.00e+00,9.00e+00,5.00e+00,2.00e+00


In [ ]:
csv = np.loadtxt('b.csv', delimiter=',')
print(csv)

[[4. 5. 5. 2. 9.]
 [4. 4. 5. 6. 2.]
 [1. 3. 5. 5. 5.]
 [1. 1. 1. 6. 1.]
 [2. 8. 9. 5. 2.]]




---

